### ISSUE TITLE
Dropdown Default Value ?

### ISSUE THREAD

**Issue by tetiolaw** [JamesLefrere/meteor-autoform-semantic-ui#14]
I don't know if it's an issue but I didn't find a way to define a default value in the dropdown list via schema definition.
```
IdCountry: { 
    type: String, min: 2, max: 2,
    autoform: {
      options: codesUE,
//       options: function () {
//         return [ { optgroup: "EUROPE", options: codesUE }, { optgroup: "OUTSIDE", options: codesNUE } ];
//	    }
//  value : 'UK'
    }
  }
```
The text commented was used before the installation of autoform-semantic-ui package and was working perfectly. Once installed autoform-semantic-ui default value (value:"UK") is not working anymore, neither the optgroup.

**Comment by tetiolaw** [comment]
Sorry defaultValue works (i don't know what was wrong in the code), but however the optgroup is still not working

**Comment by JamesLefrere** [comment]
Hi, I'd recommend using https://github.com/fabienb4/meteor-autoform-semantic-ui if you haven't already, since this repo is no longer maintained.
